import { Geist, Geist_Mono , Roboto} from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const roboto = Roboto({
  weight: ["400"],
  subsets: ['latin']
})



export const metadata = {
  title : {
    default: "learning-nextjs",
    template: "%s | learning-nextjs"
  },
   keywords: ['Next.js', 'React', 'JavaScript', 'nextjs','playground'],
  description: "Generated by sheikh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Navber></Navber>
        {children}
      </body>
    </html>
  );
}
